#!/bin/env zsh

# http://www.commandlinefu.com/commands/view/7294/backup-a-file-with-a-date-time-stamp
oldname=$1;
if [ "$oldname" != "" ]; then
    datepart=$(date +%Y-%m-%d);
    firstpart=`echo $oldname | cut -d "." -f 1`;
    newname=`echo $oldname | sed s/$firstpart/$firstpart.$datepart/`;
    cp -R ${oldname} ${newname};
fi
